### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by elsombra** [pp9999/MemReading#4]
There's no source, is that intentional? and if so do you plan on releasing a function list or updating? I just started to learn scripting and I noticed that there's a lack of interaction with the game and options

**Comment by pp9999** [comment]
Well source is secret.
Well it can't do much anyway, you can make it click goblins.
You can view all functions in Simba function list, including plugins after it has loaded plugin. Some dosen't work as they are outdated. I should make some basic function list for forums.

**Comment by elsombra** [comment]
Okay thanks for the Reply, Good work though.
